### ISSUE TITLE
Not compatible with AndroidX PreferenceFragmentCompat

### ISSUE THREAD

**Issue by artensonart98** [vanniktech/VNTFontListPreference#55] opened 2019-07-12 09:24 UTC
The main class extends from android.Preference.ListPreference.
It should rather extend from androidx.Preference.ListPreference.

Its crashing the application after migrating to AndroidX

**Comment by vanniktech** [comment] 2019-07-14 10:13
Yeah. Dupe of #54

**Closed as completed by vanniktech** 2019-07-14 10:13 UTC
